# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - run: yarn
      - run: yarn build
      - run: yarn test

  publish:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - uses: actions/checkout@v3
      - name: Install pd cli
        env:
          PD_API_KEY: ${{ secrets.PD_API_KEY }}
        run: |
          curl -O https://cli.pipedream.com/linux/amd64/latest/pd.zip
          unzip pd.zip
          mkdir -p $HOME/.config/pipedream
          echo "api_key = $PD_API_KEY" > $HOME/.config/pipedream/config
      - run: |
          ./pd new app loomio
          git status
      - uses: technote-space/create-pr-action@v2
        with:
          EXECUTE_COMMANDS: |
            ./pd new app loomio
          COMMIT_MESSAGE: "chore: update scaffold"
          COMMIT_NAME: "GitHub Actions"
          COMMIT_EMAIL: "example@example.com"
          PR_BRANCH_NAME: "chore-update-scaffold-${PR_ID}"
          PR_TITLE: "chore: update scaffold"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: ./pd publish .
