# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - run: yarn
      - run: yarn build
      - run: yarn test

  publish:
    runs-on: ubuntu-latest
    needs: [build]
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
      - name: Install pd cli
        env:
          PD_API_KEY: ${{ secrets.PD_API_KEY }}
        run: |
          curl -O https://cli.pipedream.com/linux/amd64/latest/pd.zip
          unzip pd.zip
          mkdir -p $HOME/.config/pipedream
          echo "api_key = $PD_API_KEY" > $HOME/.config/pipedream/config
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: "yarn"
      - run: yarn
      - run: yarn build
      - run: ./pd update sc_Q2ie6aB --code dist/src/actions/create-discussion.js
      - run: ./pd describe sc_Q2ie6aB
      - run: ./pd update sc_8nijGgj --code dist/src/actions/create-poll.js
